import { Recipe } from '../types';

export const CATEGORIES = ['All', 'Breakfast', 'Main', 'Appetizer', 'Dessert', 'Baking', 'Soup', 'Salad', 'Drinks', 'Other'];

export const BUILT_IN_RECIPES: Recipe[] = [
  {
    id: 'builtin-1',
    title: 'Classic Chocolate Cake',
    description: 'A rich, moist chocolate cake perfect for any occasion.',
    servings: 8,
    prepTime: 20,
    cookTime: 35,
    category: 'Dessert',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'All-purpose flour', amount: 500, unit: 'g' },
      { id: '2', name: 'Sugar', amount: 400, unit: 'g' },
      { id: '3', name: 'Cocoa powder', amount: 80, unit: 'g' },
      { id: '4', name: 'Baking soda', amount: 10, unit: 'g' },
      { id: '5', name: 'Salt', amount: 5, unit: 'g' },
      { id: '6', name: 'Eggs', amount: 2, unit: 'piece' },
      { id: '7', name: 'Buttermilk', amount: 240, unit: 'ml' },
      { id: '8', name: 'Vegetable oil', amount: 120, unit: 'ml' },
      { id: '9', name: 'Vanilla extract', amount: 10, unit: 'ml' },
      { id: '10', name: 'Boiling water', amount: 240, unit: 'ml' },
    ],
    steps: [
      'Preheat oven to 180°C (350°F). Grease two 9-inch round cake pans.',
      'Mix all dry ingredients (flour, sugar, cocoa, baking soda, salt) in a large bowl.',
      'Add eggs, buttermilk, oil, and vanilla. Beat on medium speed for 2 minutes.',
      'Stir in boiling water carefully (batter will be thin).',
      'Pour evenly into prepared pans.',
      'Bake 30-35 minutes or until a toothpick comes out clean.',
      'Cool 10 minutes before removing from pans.',
    ],
  },
  {
    id: 'builtin-2',
    title: 'Classic Pizza Dough',
    description: 'Authentic Neapolitan-style pizza dough, crispy outside and chewy inside.',
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Bread flour', amount: 500, unit: 'g' },
      { id: '2', name: 'Water (warm)', amount: 325, unit: 'ml' },
      { id: '3', name: 'Active dry yeast', amount: 7, unit: 'g' },
      { id: '4', name: 'Salt', amount: 10, unit: 'g' },
      { id: '5', name: 'Olive oil', amount: 15, unit: 'ml' },
      { id: '6', name: 'Sugar', amount: 5, unit: 'g' },
    ],
    steps: [
      'Dissolve yeast and sugar in warm water. Let sit 5 minutes until foamy.',
      'Mix flour and salt. Add yeast mixture and olive oil.',
      'Knead for 10 minutes until smooth and elastic.',
      'Cover and let rise for 1-2 hours until doubled.',
      'Punch down, divide into 4 balls.',
      'Stretch each ball into a pizza base and add toppings.',
      'Bake at 230°C (450°F) for 12-15 minutes.',
    ],
  },
  {
    id: 'builtin-3',
    title: 'Hummus',
    description: 'Creamy, authentic homemade hummus. Perfect as a dip or spread.',
    servings: 6,
    prepTime: 10,
    cookTime: 0,
    category: 'Appetizer',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Canned chickpeas', amount: 400, unit: 'g' },
      { id: '2', name: 'Tahini', amount: 60, unit: 'ml' },
      { id: '3', name: 'Lemon juice', amount: 45, unit: 'ml' },
      { id: '4', name: 'Garlic cloves', amount: 2, unit: 'clove' },
      { id: '5', name: 'Olive oil', amount: 30, unit: 'ml' },
      { id: '6', name: 'Salt', amount: 5, unit: 'g' },
      { id: '7', name: 'Cold water', amount: 60, unit: 'ml' },
      { id: '8', name: 'Paprika (for serving)', amount: 2, unit: 'g' },
    ],
    steps: [
      'Drain and rinse the chickpeas. Reserve a few for garnish.',
      'Blend chickpeas, tahini, lemon juice, and garlic until rough.',
      'Add cold water and salt; blend 4-5 minutes until ultra smooth.',
      'Taste and adjust lemon/salt.',
      'Serve in a bowl, drizzle with olive oil and sprinkle paprika.',
    ],
  },
  {
    id: 'builtin-4',
    title: 'Banana Bread',
    description: 'Moist and perfectly sweet banana bread — great for overripe bananas.',
    servings: 10,
    prepTime: 15,
    cookTime: 60,
    category: 'Baking',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Ripe bananas', amount: 3, unit: 'piece' },
      { id: '2', name: 'All-purpose flour', amount: 200, unit: 'g' },
      { id: '3', name: 'Sugar', amount: 150, unit: 'g' },
      { id: '4', name: 'Butter (melted)', amount: 80, unit: 'g' },
      { id: '5', name: 'Egg', amount: 1, unit: 'piece' },
      { id: '6', name: 'Baking soda', amount: 5, unit: 'g' },
      { id: '7', name: 'Salt', amount: 3, unit: 'g' },
      { id: '8', name: 'Vanilla extract', amount: 5, unit: 'ml' },
    ],
    steps: [
      'Preheat oven to 175°C (350°F). Grease a 9x5 inch loaf pan.',
      'Mash bananas with a fork until smooth.',
      'Mix in melted butter.',
      'Beat in egg, sugar, and vanilla.',
      'Add baking soda and salt; mix.',
      'Fold in flour gently — do not overmix.',
      'Pour into pan and bake 60-65 minutes until a toothpick comes out clean.',
    ],
  },
  {
    id: 'builtin-5',
    title: 'Classic Pancakes',
    description: 'Fluffy, golden pancakes for the perfect weekend breakfast.',
    servings: 4,
    prepTime: 5,
    cookTime: 20,
    category: 'Breakfast',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'All-purpose flour', amount: 200, unit: 'g' },
      { id: '2', name: 'Milk', amount: 300, unit: 'ml' },
      { id: '3', name: 'Egg', amount: 2, unit: 'piece' },
      { id: '4', name: 'Butter (melted)', amount: 30, unit: 'g' },
      { id: '5', name: 'Sugar', amount: 20, unit: 'g' },
      { id: '6', name: 'Baking powder', amount: 10, unit: 'g' },
      { id: '7', name: 'Salt', amount: 3, unit: 'g' },
    ],
    steps: [
      'Whisk dry ingredients (flour, baking powder, sugar, salt) together.',
      'In another bowl, mix milk, eggs, and melted butter.',
      'Pour wet into dry; stir gently until just combined (lumps are okay).',
      'Heat a non-stick pan over medium heat; lightly butter it.',
      'Pour ¼ cup batter per pancake. Cook until bubbles form, flip.',
      'Cook another 1-2 minutes until golden.',
      'Serve with maple syrup and fresh fruit.',
    ],
  },
  {
    id: 'builtin-6',
    title: 'Classic French Omelette',
    description: 'A smooth, creamy, and delicate omelette — the gold standard of eggs.',
    servings: 1,
    prepTime: 5,
    cookTime: 5,
    category: 'Breakfast',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Eggs', amount: 3, unit: 'piece' },
      { id: '2', name: 'Unsalted butter', amount: 15, unit: 'g' },
      { id: '3', name: 'Salt', amount: 1, unit: 'pinch' },
      { id: '4', name: 'Fresh chives', amount: 5, unit: 'g' },
    ],
    steps: [
      'Whisk eggs with a pinch of salt until no streaks of white remain.',
      'Heat a non-stick skillet over medium-low heat and melt the butter.',
      'Pour in the eggs and stir constantly with a spatula, shaking the pan.',
      'When eggs are mostly set but still slightly wet, stop stirring and smooth them out.',
      'Roll the omelette and slide onto a plate.',
      'Garnish with fresh chives.',
    ],
  },
  {
    id: 'builtin-7',
    title: 'Brioche French Toast',
    description: 'Thick slices of brioche soaked in a rich custard and fried until golden.',
    servings: 2,
    prepTime: 10,
    cookTime: 10,
    category: 'Breakfast',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Brioche bread', amount: 4, unit: 'slice' },
      { id: '2', name: 'Eggs', amount: 2, unit: 'piece' },
      { id: '3', name: 'Whole milk', amount: 120, unit: 'ml' },
      { id: '4', name: 'Cinnamon', amount: 2, unit: 'g' },
      { id: '5', name: 'Vanilla extract', amount: 5, unit: 'ml' },
      { id: '6', name: 'Butter', amount: 20, unit: 'g' },
    ],
    steps: [
      'Whisk eggs, milk, cinnamon, and vanilla in a shallow bowl.',
      'Soak bread slices in the mixture for 30 seconds per side.',
      'Heat butter in a skillet over medium heat.',
      'Fry bread until golden brown on both sides (about 3-4 minutes per side).',
      'Serve with maple syrup and powdered sugar.',
    ],
  },
  {
    id: 'builtin-8',
    title: 'Berry Smoothie Bowl',
    description: 'A thick, spoonable smoothie topped with fresh fruit and granola.',
    servings: 1,
    prepTime: 10,
    cookTime: 0,
    category: 'Breakfast',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Frozen mixed berries', amount: 150, unit: 'g' },
      { id: '2', name: 'Frozen banana', amount: 1, unit: 'piece' },
      { id: '3', name: 'Almond milk', amount: 100, unit: 'ml' },
      { id: '4', name: 'Granola', amount: 30, unit: 'g' },
      { id: '5', name: 'Chia seeds', amount: 5, unit: 'g' },
    ],
    steps: [
      'Blend frozen berries, banana, and almond milk until thick and smooth.',
      'Pour into a bowl.',
      'Top with granola, chia seeds, and any fresh fruit you have.',
    ],
  },
  {
    id: 'builtin-9',
    title: 'Sourdough Avocado Toast',
    description: 'The modern classic: creamy avocado on toasted sourdough with a kick.',
    servings: 1,
    prepTime: 5,
    cookTime: 5,
    category: 'Breakfast',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Sourdough bread', amount: 1, unit: 'slice' },
      { id: '2', name: 'Ripe avocado', amount: 1, unit: 'piece' },
      { id: '3', name: 'Lemon juice', amount: 5, unit: 'ml' },
      { id: '4', name: 'Red pepper flakes', amount: 1, unit: 'pinch' },
      { id: '5', name: 'Extra virgin olive oil', amount: 5, unit: 'ml' },
    ],
    steps: [
      'Toast the sourdough bread until golden and crisp.',
      'Mash the avocado in a small bowl with lemon juice and a pinch of salt.',
      'Spread the avocado on the toast.',
      'Drizzle with olive oil and sprinkle with red pepper flakes.',
    ],
  },
  {
    id: 'builtin-10',
    title: 'Pasta Carbonara',
    description: 'The authentic Roman pasta with eggs, cheese, and guanciale.',
    servings: 2,
    prepTime: 10,
    cookTime: 15,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Spaghetti', amount: 200, unit: 'g' },
      { id: '2', name: 'Guanciale or Pancetta', amount: 100, unit: 'g' },
      { id: '3', name: 'Pecorino Romano', amount: 50, unit: 'g' },
      { id: '4', name: 'Eggs', amount: 2, unit: 'piece' },
      { id: '5', name: 'Black pepper', amount: 5, unit: 'g' },
    ],
    steps: [
      'Boil spaghetti in salted water until al dente.',
      'Fry guanciale in a pan until crispy. Remove from heat.',
      'Whisk eggs and grated cheese together in a bowl.',
      'Drain pasta, reserving some water. Toss pasta with guanciale.',
      'Remove pan from heat completely. Pour egg mixture over pasta, tossing rapidly.',
      'Add pasta water as needed to create a creamy sauce. Do not scramble the eggs!',
    ],
  },
  {
    id: 'builtin-11',
    title: 'Lemon Herb Grilled Chicken',
    description: 'Juicy chicken breasts marinated in lemon, garlic, and fresh herbs.',
    servings: 2,
    prepTime: 15,
    cookTime: 15,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Chicken breast', amount: 2, unit: 'piece' },
      { id: '2', name: 'Lemon juice', amount: 30, unit: 'ml' },
      { id: '3', name: 'Garlic cloves', amount: 2, unit: 'clove' },
      { id: '4', name: 'Dried oregano', amount: 5, unit: 'g' },
      { id: '5', name: 'Olive oil', amount: 20, unit: 'ml' },
    ],
    steps: [
      'Mix lemon juice, minced garlic, oregano, and olive oil in a bag.',
      'Add chicken and marinate for at least 30 minutes.',
      'Preheat grill or pan to medium-high heat.',
      'Grill chicken for 6-7 minutes per side until internal temperature reaches 75°C.',
      'Let rest for 5 minutes before slicing.',
    ],
  },
  {
    id: 'builtin-12',
    title: 'Beef Stir Fry',
    description: 'Quick and healthy beef stir fry with colorful vegetables.',
    servings: 3,
    prepTime: 20,
    cookTime: 10,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Flank steak', amount: 400, unit: 'g' },
      { id: '2', name: 'Broccoli florets', amount: 200, unit: 'g' },
      { id: '3', name: 'Soy sauce', amount: 45, unit: 'ml' },
      { id: '4', name: 'Ginger (grated)', amount: 10, unit: 'g' },
      { id: '5', name: 'Sesame oil', amount: 15, unit: 'ml' },
      { id: '6', name: 'Bell peppers', amount: 2, unit: 'piece' },
    ],
    steps: [
      'Thinly slice the beef across the grain.',
      'Whisk soy sauce, ginger, and sesame oil for the sauce.',
      'Heat a wok or large skillet with oil until smoking.',
      'Sear beef in batches and set aside.',
      'Stir fry vegetables until tender-crisp.',
      'Add beef and sauce back to the pan; toss to coat and thicken.',
    ],
  },
  {
    id: 'builtin-13',
    title: 'Pan-Seared Salmon',
    description: 'Crispy skin salmon with a tender, flaky interior.',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Salmon fillets', amount: 2, unit: 'piece' },
      { id: '2', name: 'Olive oil', amount: 15, unit: 'ml' },
      { id: '3', name: 'Salt', amount: 2, unit: 'g' },
      { id: '4', name: 'Lemon wedges', amount: 2, unit: 'piece' },
    ],
    steps: [
      'Pat salmon skin dry with paper towels. Season with salt.',
      'Heat oil in a non-stick pan over medium-high heat.',
      'Place salmon skin-side down and press gently with a spatula.',
      'Cook for 6 minutes without moving until skin is crispy.',
      'Flip and cook for 2-3 more minutes.',
      'Serve with lemon wedges.',
    ],
  },
  {
    id: 'builtin-14',
    title: 'Garlic Butter Lamb Chops',
    description: 'Tender lamb chops seared with garlic and rosemary butter.',
    servings: 2,
    prepTime: 10,
    cookTime: 10,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Lamb chops', amount: 4, unit: 'piece' },
      { id: '2', name: 'Butter', amount: 30, unit: 'g' },
      { id: '3', name: 'Garlic cloves', amount: 3, unit: 'clove' },
      { id: '4', name: 'Fresh rosemary', amount: 2, unit: 'piece' },
    ],
    steps: [
      'Season lamb chops with salt and pepper.',
      'Heat a heavy skillet over high heat with a little oil.',
      'Sear chops for 3 minutes per side.',
      'Add butter, smashed garlic, and rosemary to the pan.',
      'Baste the lamb with the foaming butter for another minute.',
      'Let rest for 5 minutes before serving.',
    ],
  },
  {
    id: 'builtin-15',
    title: 'Vegetable Curry',
    description: 'A fragrant and warming chickpea and potato curry.',
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Chickpeas (canned)', amount: 400, unit: 'g' },
      { id: '2', name: 'Potatoes (cubed)', amount: 300, unit: 'g' },
      { id: '3', name: 'Coconut milk', amount: 400, unit: 'ml' },
      { id: '4', name: 'Curry powder', amount: 20, unit: 'g' },
      { id: '5', name: 'Onion', amount: 1, unit: 'piece' },
    ],
    steps: [
      'Sauté chopped onion in oil until soft.',
      'Add curry powder and cook for 1 minute until fragrant.',
      'Add potatoes and chickpeas; stir to coat.',
      'Pour in coconut milk and simmer for 20-25 minutes until potatoes are tender.',
      'Serve with rice or naan.',
    ],
  },
  {
    id: 'builtin-16',
    title: 'Chicken Shawarma',
    description: 'Middle Eastern style marinated chicken, perfect for wraps.',
    servings: 4,
    prepTime: 20,
    cookTime: 20,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Chicken thighs', amount: 600, unit: 'g' },
      { id: '2', name: 'Cumin', amount: 5, unit: 'g' },
      { id: '3', name: 'Paprika', amount: 5, unit: 'g' },
      { id: '4', name: 'Garlic powder', amount: 5, unit: 'g' },
      { id: '5', name: 'Yogurt', amount: 120, unit: 'ml' },
    ],
    steps: [
      'Marinate chicken in yogurt and spices for at least 2 hours.',
      'Preheat oven to 200°C (400°F).',
      'Place chicken on a baking sheet and roast for 20 minutes.',
      'Switch to broiler for 2-3 minutes to get charred edges.',
      'Thinly slice and serve in pita with tahini sauce.',
    ],
  },
  {
    id: 'builtin-17',
    title: 'Homemade Falafel',
    description: 'Crispy herb-packed chickpea fritters.',
    servings: 4,
    prepTime: 30,
    cookTime: 10,
    category: 'Main',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Dried chickpeas (soaked)', amount: 250, unit: 'g' },
      { id: '2', name: 'Fresh parsley', amount: 50, unit: 'g' },
      { id: '3', name: 'Fresh cilantro', amount: 50, unit: 'g' },
      { id: '4', name: 'Garlic cloves', amount: 4, unit: 'clove' },
      { id: '5', name: 'Baking powder', amount: 5, unit: 'g' },
    ],
    steps: [
      'Process soaked chickpeas, herbs, and garlic in a food processor until grainy but not puréed.',
      'Stir in salt and baking powder. Chill for 30 minutes.',
      'Form into small balls.',
      'Deep fry in oil at 180°C until dark golden brown.',
      'Serve hot with tahini.',
    ],
  },
  {
    id: 'builtin-18',
    title: 'Tomato Bruschetta',
    description: 'Crispy toasted bread topped with fresh tomato and basil.',
    servings: 4,
    prepTime: 15,
    cookTime: 5,
    category: 'Appetizer',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Baguette', amount: 1, unit: 'piece' },
      { id: '2', name: 'Roma tomatoes', amount: 4, unit: 'piece' },
      { id: '3', name: 'Fresh basil', amount: 10, unit: 'g' },
      { id: '4', name: 'Garlic cloves', amount: 1, unit: 'clove' },
      { id: '5', name: 'Olive oil', amount: 30, unit: 'ml' },
    ],
    steps: [
      'Dice tomatoes and mix with chopped basil, olive oil, and salt.',
      'Slice baguette and toast until golden.',
      'Rub a raw garlic clove onto the toasted bread.',
      'Spoon tomato mixture onto the bread just before serving.',
    ],
  },
  {
    id: 'builtin-19',
    title: 'Vegetable Spring Rolls',
    description: 'Crispy pastry filled with shredded vegetables.',
    servings: 4,
    prepTime: 30,
    cookTime: 10,
    category: 'Appetizer',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Spring roll wrappers', amount: 12, unit: 'piece' },
      { id: '2', name: 'Cabbage (shredded)', amount: 200, unit: 'g' },
      { id: '3', name: 'Carrots (julienned)', amount: 100, unit: 'g' },
      { id: '4', name: 'Soy sauce', amount: 15, unit: 'ml' },
      { id: '5', name: 'Ginger', amount: 5, unit: 'g' },
    ],
    steps: [
      'Sauté cabbage, carrots, and ginger with soy sauce until wilted.',
      'Let filling cool completely.',
      'Place filling on a wrapper and roll tightly, sealing with water.',
      'Deep fry until golden and crispy.',
    ],
  },
  {
    id: 'builtin-20',
    title: 'Stuffed Mushrooms',
    description: 'Mushroom caps filled with garlic, herbs, and breadcrumbs.',
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    category: 'Appetizer',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Cremini mushrooms', amount: 12, unit: 'piece' },
      { id: '2', name: 'Breadcrumbs', amount: 50, unit: 'g' },
      { id: '3', name: 'Parmesan cheese', amount: 30, unit: 'g' },
      { id: '4', name: 'Garlic cloves', amount: 2, unit: 'clove' },
      { id: '5', name: 'Butter (melted)', amount: 20, unit: 'g' },
    ],
    steps: [
      'Remove stems from mushrooms and chop stems finely.',
      'Sauté stems and garlic in butter.',
      'Mix with breadcrumbs and parmesan.',
      'Fill mushroom caps with the mixture.',
      'Bake at 190°C (375°F) for 20 minutes.',
    ],
  },
  {
    id: 'builtin-21',
    title: 'Cheesy Garlic Bread',
    description: 'Buttery, garlicky, and loaded with melted mozzarella.',
    servings: 6,
    prepTime: 10,
    cookTime: 10,
    category: 'Appetizer',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Italian loaf', amount: 1, unit: 'piece' },
      { id: '2', name: 'Butter (softened)', amount: 100, unit: 'g' },
      { id: '3', name: 'Garlic cloves', amount: 4, unit: 'clove' },
      { id: '4', name: 'Mozzarella cheese', amount: 150, unit: 'g' },
      { id: '5', name: 'Parsley', amount: 5, unit: 'g' },
    ],
    steps: [
      'Mix butter, minced garlic, and parsley.',
      'Slice bread in half lengthwise.',
      'Spread garlic butter on both halves.',
      'Top with cheese and bake at 200°C until bubbly and golden.',
    ],
  },
  {
    id: 'builtin-22',
    title: 'Classic Caprese Salad',
    description: 'Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze.',
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    category: 'Appetizer',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Fresh mozzarella', amount: 200, unit: 'g' },
      { id: '2', name: 'Tomatoes', amount: 2, unit: 'piece' },
      { id: '3', name: 'Fresh basil', amount: 10, unit: 'g' },
      { id: '4', name: 'Balsamic glaze', amount: 15, unit: 'ml' },
      { id: '5', name: 'Olive oil', amount: 15, unit: 'ml' },
    ],
    steps: [
      'Slice tomatoes and mozzarella into 1cm thick rounds.',
      'Layer them on a plate, alternating with basil leaves.',
      'Drizzle with olive oil and balsamic glaze.',
      'Season with salt and pepper.',
    ],
  },
  {
    id: 'builtin-23',
    title: 'Classic Tiramisu',
    description: 'An elegant Italian dessert with espresso-soaked ladyfingers and mascarpone.',
    servings: 6,
    prepTime: 30,
    cookTime: 0,
    category: 'Dessert',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Mascarpone cheese', amount: 500, unit: 'g' },
      { id: '2', name: 'Ladyfingers (Savoiardi)', amount: 24, unit: 'piece' },
      { id: '3', name: 'Strong espresso (cooled)', amount: 240, unit: 'ml' },
      { id: '4', name: 'Eggs', amount: 3, unit: 'piece' },
      { id: '5', name: 'Sugar', amount: 100, unit: 'g' },
      { id: '6', name: 'Cocoa powder', amount: 20, unit: 'g' },
    ],
    steps: [
      'Separate eggs. Whisk yolks with sugar until pale.',
      'Fold in mascarpone until smooth.',
      'Whisk egg whites to stiff peaks and fold into the mascarpone mixture.',
      'Quickly dip ladyfingers in espresso and layer in a dish.',
      'Spread half the cream over. Repeat with another layer of fingers and cream.',
      'Refrigerate for 6 hours. Dust with cocoa powder before serving.',
    ],
  },
  {
    id: 'builtin-24',
    title: 'New York Cheesecake',
    description: 'Rich, dense, and creamy cheesecake with a graham cracker crust.',
    servings: 12,
    prepTime: 20,
    cookTime: 60,
    category: 'Dessert',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Cream cheese', amount: 900, unit: 'g' },
      { id: '2', name: 'Sugar', amount: 200, unit: 'g' },
      { id: '3', name: 'Eggs', amount: 4, unit: 'piece' },
      { id: '4', name: 'Graham cracker crumbs', amount: 200, unit: 'g' },
      { id: '5', name: 'Butter (melted)', amount: 60, unit: 'g' },
    ],
    steps: [
      'Mix crumbs and butter; press into the bottom of a springform pan.',
      'Beat cream cheese and sugar until smooth.',
      'Add eggs one at a time on low speed.',
      'Pour over crust. Bake at 160°C (325°F) for 60 minutes.',
      'Turn off oven and let cool inside with the door cracked for 1 hour.',
      'Chill overnight.',
    ],
  },
  {
    id: 'builtin-25',
    title: 'Fudgy Brownies',
    description: 'Dense, chewy chocolate brownies with a crackly top.',
    servings: 12,
    prepTime: 15,
    cookTime: 25,
    category: 'Dessert',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Butter', amount: 170, unit: 'g' },
      { id: '2', name: 'Chocolate chips', amount: 200, unit: 'g' },
      { id: '3', name: 'Sugar', amount: 200, unit: 'g' },
      { id: '4', name: 'Eggs', amount: 3, unit: 'piece' },
      { id: '5', name: 'All-purpose flour', amount: 100, unit: 'g' },
    ],
    steps: [
      'Melt butter and chocolate together.',
      'Whisk in sugar, then eggs one by one.',
      'Fold in flour and a pinch of salt.',
      'Pour into a lined square pan.',
      'Bake at 180°C for 25 minutes. Do not overbake!',
    ],
  },
  {
    id: 'builtin-26',
    title: 'Homemade Apple Pie',
    description: 'Classic warm apple pie with a flaky buttery crust.',
    servings: 8,
    prepTime: 40,
    cookTime: 50,
    category: 'Dessert',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Apples (peeled/sliced)', amount: 6, unit: 'piece' },
      { id: '2', name: 'Pie crust dough', amount: 2, unit: 'piece' },
      { id: '3', name: 'Sugar', amount: 150, unit: 'g' },
      { id: '4', name: 'Cinnamon', amount: 5, unit: 'g' },
      { id: '5', name: 'Butter', amount: 30, unit: 'g' },
    ],
    steps: [
      'Toss apples with sugar and cinnamon.',
      'Line a pie dish with one crust.',
      'Fill with apples and dot with butter.',
      'Cover with the second crust, seal edges, and cut vents.',
      'Bake at 190°C (375°F) for 45-50 minutes.',
    ],
  },
  {
    id: 'builtin-27',
    title: 'Vanilla Bean Creme Brulee',
    description: 'Smooth vanilla custard with a brittle caramelized sugar top.',
    servings: 4,
    prepTime: 15,
    cookTime: 40,
    category: 'Dessert',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Heavy cream', amount: 500, unit: 'ml' },
      { id: '2', name: 'Egg yolks', amount: 5, unit: 'piece' },
      { id: '3', name: 'Sugar', amount: 100, unit: 'g' },
      { id: '4', name: 'Vanilla bean', amount: 1, unit: 'piece' },
    ],
    steps: [
      'Heat cream with vanilla seeds until just simmering.',
      'Whisk yolks and half the sugar.',
      'Slowly temper the cream into the yolks.',
      'Pour into ramekins. Bake in a water bath at 150°C for 40 minutes.',
      'Chill for 4 hours. Sprinkle sugar on top and caramelize with a torch.',
    ],
  },
  {
    id: 'builtin-28',
    title: 'Honey Walnut Baklava',
    description: 'Layers of crispy phyllo pastry, nuts, and sweet honey syrup.',
    servings: 12,
    prepTime: 45,
    cookTime: 50,
    category: 'Dessert',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Phyllo dough', amount: 1, unit: 'piece' },
      { id: '2', name: 'Walnuts (chopped)', amount: 300, unit: 'g' },
      { id: '3', name: 'Butter (melted)', amount: 200, unit: 'g' },
      { id: '4', name: 'Honey', amount: 200, unit: 'ml' },
      { id: '5', name: 'Sugar', amount: 100, unit: 'g' },
    ],
    steps: [
      'Layer phyllo sheets in a pan, brushing each with butter.',
      'Add a layer of walnuts every few sheets.',
      'Cut into diamonds before baking.',
      'Bake at 175°C for 50 minutes until golden.',
      'Immediately pour cooled honey-sugar syrup over the hot pastry.',
    ],
  },
  {
    id: 'builtin-29',
    title: 'Classic Sourdough Bread',
    description: 'A traditional crusty loaf made with natural yeast.',
    servings: 1,
    prepTime: 60,
    cookTime: 45,
    category: 'Baking',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Bread flour', amount: 500, unit: 'g' },
      { id: '2', name: 'Water', amount: 350, unit: 'ml' },
      { id: '3', name: 'Sourdough starter', amount: 100, unit: 'g' },
      { id: '4', name: 'Salt', amount: 10, unit: 'g' },
    ],
    steps: [
      'Mix flour, water, and starter. Let rest for 30 minutes.',
      'Add salt and perform folds every 30 minutes for 2 hours.',
      'Let bulk ferment until 50% larger.',
      'Shape and proof in a basket for 2-4 hours or overnight in the fridge.',
      'Bake in a Dutch oven at 230°C for 20 mins covered, 25 mins uncovered.',
    ],
  },
  {
    id: 'builtin-30',
    title: 'Butter Croissants',
    description: 'Flaky, buttery, multi-layered French pastries.',
    servings: 6,
    prepTime: 120,
    cookTime: 20,
    category: 'Baking',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Bread flour', amount: 500, unit: 'g' },
      { id: '2', name: 'Butter (cold)', amount: 250, unit: 'g' },
      { id: '3', name: 'Milk', amount: 250, unit: 'ml' },
      { id: '4', name: 'Yeast', amount: 10, unit: 'g' },
      { id: '5', name: 'Sugar', amount: 50, unit: 'g' },
    ],
    steps: [
      'Make a dough and let it rest.',
      'Create a flat butter block.',
      'Fold the butter into the dough (lamination) with three "turns".',
      'Roll out, cut into triangles, and roll up.',
      'Proof for 2 hours and bake at 200°C until golden.',
    ],
  },
  {
    id: 'builtin-31',
    title: 'Soft Cinnamon Rolls',
    description: 'Gooey and sweet rolls with a cream cheese glaze.',
    servings: 12,
    prepTime: 40,
    cookTime: 25,
    category: 'Baking',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'All-purpose flour', amount: 500, unit: 'g' },
      { id: '2', name: 'Butter', amount: 100, unit: 'g' },
      { id: '3', name: 'Brown sugar', amount: 150, unit: 'g' },
      { id: '4', name: 'Cinnamon', amount: 15, unit: 'g' },
      { id: '5', name: 'Cream cheese', amount: 100, unit: 'g' },
    ],
    steps: [
      'Make a sweet yeast dough and let rise.',
      'Roll into a rectangle, spread butter, sugar, and cinnamon.',
      'Roll up tightly and slice.',
      'Let rise again, then bake at 180°C for 25 minutes.',
      'Frost while warm with cream cheese glaze.',
    ],
  },
  {
    id: 'builtin-32',
    title: 'Rosemary Focaccia',
    description: 'A flat Italian bread topped with olive oil and fresh rosemary.',
    servings: 8,
    prepTime: 20,
    cookTime: 20,
    category: 'Baking',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Bread flour', amount: 500, unit: 'g' },
      { id: '2', name: 'Warm water', amount: 400, unit: 'ml' },
      { id: '3', name: 'Yeast', amount: 7, unit: 'g' },
      { id: '4', name: 'Olive oil', amount: 60, unit: 'ml' },
      { id: '5', name: 'Fresh rosemary', amount: 10, unit: 'g' },
    ],
    steps: [
      'Mix a very wet dough and let rise until bubbly.',
      'Pour into a greased pan and stretch.',
      'Dimple the surface with fingers, add oil and rosemary.',
      'Bake at 220°C until golden and crisp.',
    ],
  },
  {
    id: 'builtin-33',
    title: 'Homemade Pita Bread',
    description: 'Soft, pocketed flatbreads fresh from the oven.',
    servings: 8,
    prepTime: 60,
    cookTime: 5,
    category: 'Baking',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'All-purpose flour', amount: 400, unit: 'g' },
      { id: '2', name: 'Yeast', amount: 7, unit: 'g' },
      { id: '3', name: 'Warm water', amount: 250, unit: 'ml' },
      { id: '4', name: 'Salt', amount: 5, unit: 'g' },
    ],
    steps: [
      'Knead flour, water, yeast, and salt into a smooth dough.',
      'Let rise for 1 hour.',
      'Divide into 8 balls and roll into thin circles.',
      'Bake on a preheated stone or tray at 250°C for 3-5 minutes until puffed.',
    ],
  },
  {
    id: 'builtin-34',
    title: 'Creamy Tomato Soup',
    description: 'Smooth and comforting roasted tomato soup.',
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    category: 'Soup',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Canned tomatoes', amount: 800, unit: 'g' },
      { id: '2', name: 'Onion', amount: 1, unit: 'piece' },
      { id: '3', name: 'Garlic', amount: 3, unit: 'clove' },
      { id: '4', name: 'Vegetable broth', amount: 500, unit: 'ml' },
      { id: '5', name: 'Heavy cream', amount: 100, unit: 'ml' },
    ],
    steps: [
      'Sauté onion and garlic.',
      'Add tomatoes and broth. Simmer for 20 minutes.',
      'Blend until smooth.',
      'Stir in cream and season to taste.',
    ],
  },
  {
    id: 'builtin-35',
    title: 'Red Lentil Soup',
    description: 'A hearty and healthy Mediterranean lentil soup.',
    servings: 4,
    prepTime: 10,
    cookTime: 25,
    category: 'Soup',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Red lentils', amount: 200, unit: 'g' },
      { id: '2', name: 'Carrot', amount: 1, unit: 'piece' },
      { id: '3', name: 'Cumin', amount: 5, unit: 'g' },
      { id: '4', name: 'Vegetable broth', amount: 1, unit: 'l' },
      { id: '5', name: 'Lemon', amount: 1, unit: 'piece' },
    ],
    steps: [
      'Sauté diced carrot and cumin.',
      'Add lentils and broth.',
      'Simmer for 20 minutes until lentils are soft.',
      'Partially blend for texture. Serve with a squeeze of lemon.',
    ],
  },
  {
    id: 'builtin-36',
    title: 'Classic Chicken Noodle Soup',
    description: 'The ultimate feel-good soup with tender chicken and egg noodles.',
    servings: 6,
    prepTime: 15,
    cookTime: 40,
    category: 'Soup',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Chicken breast', amount: 400, unit: 'g' },
      { id: '2', name: 'Egg noodles', amount: 150, unit: 'g' },
      { id: '3', name: 'Carrots', amount: 2, unit: 'piece' },
      { id: '4', name: 'Celery stalks', amount: 2, unit: 'piece' },
      { id: '5', name: 'Chicken broth', amount: 1.5, unit: 'l' },
    ],
    steps: [
      'Sauté carrots and celery in a pot.',
      'Add broth and chicken. Simmer until chicken is cooked.',
      'Remove chicken, shred it, and return to the pot.',
      'Add noodles and cook until tender.',
    ],
  },
  {
    id: 'builtin-37',
    title: 'French Onion Soup',
    description: 'Deeply caramelized onions in a rich beef broth with melted cheese.',
    servings: 4,
    prepTime: 15,
    cookTime: 60,
    category: 'Soup',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Onions', amount: 4, unit: 'piece' },
      { id: '2', name: 'Beef broth', amount: 1, unit: 'l' },
      { id: '3', name: 'Gruyere cheese', amount: 100, unit: 'g' },
      { id: '4', name: 'Baguette slices', amount: 4, unit: 'piece' },
      { id: '5', name: 'Butter', amount: 50, unit: 'g' },
    ],
    steps: [
      'Slowly cook onions in butter for 45 minutes until dark brown.',
      'Add broth and simmer for 15 minutes.',
      'Ladle into bowls, top with toasted bread and cheese.',
      'Broil until cheese is melted and bubbly.',
    ],
  },
  {
    id: 'builtin-38',
    title: 'Classic Caesar Salad',
    description: 'Crisp romaine lettuce with creamy dressing and croutons.',
    servings: 2,
    prepTime: 15,
    cookTime: 5,
    category: 'Salad',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Romaine lettuce', amount: 1, unit: 'piece' },
      { id: '2', name: 'Caesar dressing', amount: 60, unit: 'ml' },
      { id: '3', name: 'Croutons', amount: 50, unit: 'g' },
      { id: '4', name: 'Parmesan cheese', amount: 30, unit: 'g' },
    ],
    steps: [
      'Chop lettuce into bite-sized pieces.',
      'Toss with dressing, croutons, and cheese.',
      'Serve immediately to keep croutons crunchy.',
    ],
  },
  {
    id: 'builtin-39',
    title: 'Traditional Greek Salad',
    description: 'A refreshing mix of cucumbers, tomatoes, olives, and feta.',
    servings: 2,
    prepTime: 15,
    cookTime: 0,
    category: 'Salad',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Cucumber', amount: 1, unit: 'piece' },
      { id: '2', name: 'Tomatoes', amount: 2, unit: 'piece' },
      { id: '3', name: 'Feta cheese', amount: 100, unit: 'g' },
      { id: '4', name: 'Kalamata olives', amount: 50, unit: 'g' },
      { id: '5', name: 'Red onion', amount: 0.5, unit: 'piece' },
    ],
    steps: [
      'Chop vegetables into large chunks.',
      'Mix in a bowl with olives.',
      'Top with a slab of feta cheese and drizzle with olive oil and oregano.',
    ],
  },
  {
    id: 'builtin-40',
    title: 'Fresh Tabbouleh',
    description: 'A vibrant Lebanese herb salad with bulgur and parsley.',
    servings: 4,
    prepTime: 25,
    cookTime: 0,
    category: 'Salad',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Fresh parsley', amount: 200, unit: 'g' },
      { id: '2', name: 'Bulgur (fine)', amount: 50, unit: 'g' },
      { id: '3', name: 'Tomatoes', amount: 3, unit: 'piece' },
      { id: '4', name: 'Lemon juice', amount: 60, unit: 'ml' },
      { id: '5', name: 'Olive oil', amount: 60, unit: 'ml' },
    ],
    steps: [
      'Soak bulgur in water for 15 minutes, then drain.',
      'Finely chop parsley and tomatoes.',
      'Mix all ingredients in a bowl.',
      'Chill for 30 minutes before serving.',
    ],
  },
  {
    id: 'builtin-41',
    title: 'Lebanese Fattoush',
    description: 'A zesty salad with toasted pita and sumac dressing.',
    servings: 4,
    prepTime: 20,
    cookTime: 5,
    category: 'Salad',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Romaine lettuce', amount: 1, unit: 'piece' },
      { id: '2', name: 'Radishes', amount: 4, unit: 'piece' },
      { id: '3', name: 'Pita bread', amount: 1, unit: 'piece' },
      { id: '4', name: 'Sumac', amount: 5, unit: 'g' },
      { id: '5', name: 'Lemon juice', amount: 30, unit: 'ml' },
    ],
    steps: [
      'Toast or fry pita bread until crispy and break into pieces.',
      'Chop vegetables and mix with pita.',
      'Dress with lemon juice, olive oil, and plenty of sumac.',
    ],
  },
  {
    id: 'builtin-42',
    title: 'Fresh Lemonade',
    description: 'Homemade lemonade with the perfect balance of sweet and tart.',
    servings: 4,
    prepTime: 10,
    cookTime: 5,
    category: 'Drinks',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Lemons', amount: 6, unit: 'piece' },
      { id: '2', name: 'Sugar', amount: 150, unit: 'g' },
      { id: '3', name: 'Water', amount: 1, unit: 'l' },
      { id: '4', name: 'Ice cubes', amount: 10, unit: 'piece' },
    ],
    steps: [
      'Make a simple syrup by heating sugar and 1 cup of water until dissolved.',
      'Squeeze the lemons.',
      'Mix lemon juice, syrup, and remaining water.',
      'Serve over ice.',
    ],
  },
  {
    id: 'builtin-43',
    title: 'Moroccan Mint Tea',
    description: 'Traditional green tea with fresh mint and plenty of sugar.',
    servings: 4,
    prepTime: 5,
    cookTime: 10,
    category: 'Drinks',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Green tea (gunpowder)', amount: 10, unit: 'g' },
      { id: '2', name: 'Fresh mint', amount: 50, unit: 'g' },
      { id: '3', name: 'Sugar', amount: 50, unit: 'g' },
      { id: '4', name: 'Water', amount: 800, unit: 'ml' },
    ],
    steps: [
      'Rinse tea leaves with boiling water.',
      'Boil tea with water for a few minutes.',
      'Add fresh mint and sugar to the pot.',
      'Let steep for 5 minutes and pour from a height to create foam.',
    ],
  },
  {
    id: 'builtin-44',
    title: 'Tropical Fruit Smoothie',
    description: 'A refreshing blend of mango, pineapple, and coconut.',
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    category: 'Drinks',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Mango (frozen)', amount: 200, unit: 'g' },
      { id: '2', name: 'Pineapple (frozen)', amount: 200, unit: 'g' },
      { id: '3', name: 'Coconut milk', amount: 300, unit: 'ml' },
      { id: '4', name: 'Honey', amount: 15, unit: 'ml' },
    ],
    steps: [
      'Place all ingredients in a blender.',
      'Blend on high until smooth.',
      'Pour into glasses and garnish with a pineapple wedge.',
    ],
  },
  {
    id: 'builtin-45',
    title: 'Creamy Hot Chocolate',
    description: 'Rich hot chocolate made with real chocolate and milk.',
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    category: 'Drinks',
    isBuiltIn: true,
    createdAt: '2024-01-01',
    ingredients: [
      { id: '1', name: 'Whole milk', amount: 500, unit: 'ml' },
      { id: '2', name: 'Dark chocolate', amount: 100, unit: 'g' },
      { id: '3', name: 'Sugar', amount: 20, unit: 'g' },
      { id: '4', name: 'Whipped cream', amount: 50, unit: 'g' },
    ],
    steps: [
      'Heat milk and sugar until hot but not boiling.',
      'Add chopped chocolate and whisk until melted and smooth.',
      'Pour into mugs and top with whipped cream.',
    ],
  },
];
